Models/Carros.cs
namespace HTMLtoPDF.Models
{
    public class Carros
    {
        public string Placa { get; set; }
        public string Color { get; set;}
        public string Marca { get; set;}
        public string Modelo { get; set;}
        public string Tipo { get; set;}
    }
}

Models/ErrorViewModel.cs
namespace HTMLtoPDF.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/HTMLtoPDFController.cs
using HTMLtoPDF.Models;
using Microsoft.AspNetCore.Mvc;
using Rotativa.AspNetCore;

namespace HTMLtoPDF.Controllers
{
    public class HTMLtoPDFController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        // Vista que se va a convertir en pdf
        // nuget rotativa aspnetcore
        // colocar carpeta rotativa en wwwroot
        // modificar Program.cs
        public Task<IActionResult> GenerarPDF()
        {
            List<Carros> carro = new List<Carros>()
            {
                new Carros(){ Placa = "Q3W4E5", Color = "Rojo", Modelo = "Hilux", Marca = "Toyota", Tipo = "Carga"},
                new Carros(){ Placa = "Q4W5E6", Color = "Verde", Modelo = "Hilux", Marca = "Toyota", Tipo = "Carga"},
                new Carros(){ Placa = "Q6W7E8", Color = "Azul", Modelo = "Hilux", Marca = "Toyota", Tipo = "Carga" }
            };

            return Task.FromResult<IActionResult>(new ViewAsPdf("GenerarPDF", carro)
            {
                FileName = $"HTMLtoPDF.pdf", // nombre del documento
                PageOrientation = Rotativa.AspNetCore.Options.Orientation.Portrait,
                PageSize = Rotativa.AspNetCore.Options.Size.A4
            });
        }
    }
}

Controllers/HomeController.cs
using HTMLtoPDF.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace HTMLtoPDF.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/HTMLtoPDF/GenerarPDF.cshtml
@model List<Carros>
@{
	Layout = null;
}

<DOCTYPE html>

	<table style="width:100%">
		<tbody>
			<tr>
				<td style="width:20%"><img alt="logo" src="https://supermercadosnacional.com/media/catalog/product/placeholder/default/IMG_NO_DISPONIBLE_1.png" /></td>
				<td style="vertical-align:top; width:60%">
					<table style="width:704px">
						<tbody>
							<tr>
								<td style="width:692px">
									<h4 style="margin-left:0px; margin-right:0px; text-align:center"><strong>HTMLtoPDF</strong></h4>
								</td>
							</tr>
							<tr>
								<td style="text-align:center; width:692px">XXXXXXXXXXXXXXXXXXXXXXXXX</td>
							</tr>
							<tr>
								<td style="text-align:center; width:692px">XXXXXXXXXXXXXXXXXXXXXXXXXXXX</td>
							</tr>
						</tbody>
					</table>
				</td>
				<td style="width:20%">&nbsp;</td>
			</tr>
			<tr>
				<td colspan="3">&nbsp;</td>
			</tr>
			<tr>
				<td colspan="2">
					<table style="width:100%">
						<tbody>
							<tr>
								<td colspan="1" style="width:20%">XXXXXXXXXXXXXXXXXXXXXXXXX</td>
								<td colspan="3" style="border-bottom:1px solid black; width:80%">XXXXXXXXXXXXXXXXXXXXXXXXXX</td>
							</tr>
						</tbody>
					</table>

					<table style="width:100%">
						<tbody>
							<tr>
								<td style="width:20%">Documento:</td>
								<td style="border-bottom:1px solid black; width:30%">XXXXXXXXXXXXXXXXXXXX</td>
								<td style="width:10%">XXXXXXXXXXXXXXXX</td>
								<td style="border-bottom:1px solid black; width:40%">XXXXXXXXXXXXXXXXXXXXX</td>
							</tr>
						</tbody>
					</table>
				</td>
				<td>&nbsp;</td>
			</tr>
			<tr>
				<td colspan="3">&nbsp;</td>
			</tr>
			<tr>
				<td colspan="3">
					<table class="tbproductos" style="width:100%">
						<thead>
							<tr>
								<th class="tbth">xxxxxxxxxxxxxx</th>
								<th class="tbth">xxxxxxxxxxxxxx</th>
								<th class="tbth" style="width:130px">xxxxxxxxxxxxxx</th>
								<th class="tbth" style="width:130px">xxxxxxxxxxxxxx</th>
								<th class="tbth" style="width:130px">xxxxxxxxxxxxxx</th>

							</tr>
						</thead>

						<tbody>
							@{
								foreach (Carros item in Model)
								{
									<tr>
										<td class="td-item"><p class="item">@item.Placa</p></td>
										<td class="td-item"><p class="item">@item.Marca</p></td>
										<td class="td-item"><p class="item">@item.Modelo</p></td>
										<td class="td-item"><p class="item">@item.Color</p></td>
										<td class="td-item"><p class="item">@item.Tipo</p></td>
									</tr>
								}
							}
						</tbody>
					</table>
				</td>
			</tr>
		</tbody>
	</table>
</DOCTYPE>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

<a asp-controller="HTMLtoPDF" asp-action="GenerarPDF">Generar Reporte</a>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HTMLtoPDF</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HTMLtoPDF.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HTMLtoPDF</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - HTMLtoPDF - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>